### ISSUE TITLE
static site generator

### ISSUE THREAD

**Issue by arademaker** [leanprover/verso#32]
If the use as static site generator is a goal as one possible genre, I would like to ask if is it too soon to start thinking about:

1. support for bibliography from bibtex http://arademaker.github.io/publications.html
2. support for a directory reader to automatically grab the posts available.

If possible, I would appreciate directions on the proper use of verso in a project instead of the instantiation of a website inside the folder structure of verso code.

**Comment by david-christiansen** [comment]
For 1, you should be able to implement a library in Lean that does what you want. Verso is designed to be extensible! If you try this and run into blockers, please let me know, and I'll try to figure out what we need to make it more extensible. I suspect you _might_ run into issues with the traversal state for the website genre not being extensible, because you'll probably need a pass to collect all citation occurrences - if that's the case, then I can look into making the state work more like Lean environment extensions.

I don't plan to implement 2 as part of the builtin website genre, because it's a big break with how Lean normally works. Verso documents are Lean programs, so they'll follow Lean's module system. And right now, module imports aren't something that we can really do with metaprogramming (as far as I know), though it would be fun to try! This will mean that Verso-based blogs will require 1-2 lines of code per post more than something like Hakyll, but I think this is an OK tradeoff.

Directions for using Verso will come in time - for now, any docs that I write will quickly become out of date. But when things settle down, expect a detailed user's guide that covers what you're looking for.

I'm closing this one, because I don't think there's any actionable things to keep track of for the future (other than "document it", but that's clearly on the roadmap without needing an issue).
